// Code generated by hertz generator.

package main

import (
	"github.com/acblacktea/payment_system/payment_gateway/biz/handler/acblacktea/payment_system/payment_gateway"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	payment_gateway.InitClient()
	h := server.Default()
	register(h)
	h.Spin()
}
