// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	acblacktea_payment_system_payment_gateway "github.com/acblacktea/payment_system/payment_gateway/biz/router/acblacktea/payment_system/payment_gateway"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	acblacktea_payment_system_payment_gateway.Register(r)
}
