// Code generated by Kitex v0.9.1. DO NOT EDIT.

package paymentsystem

import (
	"context"
	payment_system "github.com/acblacktea/payment_system/payment_gateway/kitex_gen/acblacktea/payment_system/payment_system"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateAccount(ctx context.Context, req *payment_system.CreateAccountRequest, callOptions ...callopt.Option) (r *payment_system.CreateAccountResponse, err error)
	GetAccount(ctx context.Context, req *payment_system.GetAccountRequest, callOptions ...callopt.Option) (r *payment_system.GetAccountResponse, err error)
	SubmitTransaction(ctx context.Context, req *payment_system.SubimitTransactionRequest, callOptions ...callopt.Option) (r *payment_system.SubimitTransactionResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kPaymentSystemClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPaymentSystemClient struct {
	*kClient
}

func (p *kPaymentSystemClient) CreateAccount(ctx context.Context, req *payment_system.CreateAccountRequest, callOptions ...callopt.Option) (r *payment_system.CreateAccountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateAccount(ctx, req)
}

func (p *kPaymentSystemClient) GetAccount(ctx context.Context, req *payment_system.GetAccountRequest, callOptions ...callopt.Option) (r *payment_system.GetAccountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAccount(ctx, req)
}

func (p *kPaymentSystemClient) SubmitTransaction(ctx context.Context, req *payment_system.SubimitTransactionRequest, callOptions ...callopt.Option) (r *payment_system.SubimitTransactionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SubmitTransaction(ctx, req)
}
