// Code generated by hertz generator.

package payment_gateway

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createaccountMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getaccountMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submittransactionMw() []app.HandlerFunc {
	// your code...
	return nil
}
